# Generated by Django 5.1.7 on 2025-03-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='emotion',
            field=models.CharField(max_length=20),
        ),
    ]
