# Generated by Django 5.1.7 on 2025-03-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_userinput_emotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='emotion',
            field=models.CharField(default='neutral', max_length=255),
        ),
    ]
